@startuml

' Interfaces
interface MessageSender {
    +send(content: String)
}

' Concrete Implementations
class EmailSender implements MessageSender {
    +send(content: String)
}

class SmsSender implements MessageSender {
    +send(content: String)
}

' Abstraction
abstract class Message {
    -messageSender: MessageSender
    +Message(messageSender: MessageSender)
    +writeMessage(content: String)
}

' Refined Abstractions
class TextMessage extends Message {
    +writeMessage(content: String)
}

class AlertMessage extends Message {
    +writeMessage(content: String)
}



Message *-- MessageSender


@enduml
